name: 'Set issue status'

on:
  project_card:
    types: [created, edited, moved]

jobs:
  set-state:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v2
        with:
          github-token: ${{ github.token }}
          open-issue-columns: 'Backlog, Ready to Go, In Progress, Testing'
          closed-issue-columns: 'Done'
